# Generated by Django 5.1.2 on 2024-10-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_readlist_watchlist_delete_watchlistreadlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mbti_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
