# Generated by Django 5.1.2 on 2024-10-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_user_mbti_type_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mbti_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.mbtitype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
