# Generated by Django 5.1.2 on 2024-10-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
