# Generated by Django 5.1.2 on 2024-10-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_username_user_user_name_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='User',
        ),
    ]
