# Generated by Django 5.1.2 on 2024-10-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_user_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
