# Generated by Django 5.1.2 on 2024-10-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_book.jpg', upload_to='book_images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default_movie.jpg', upload_to='movie_images/'),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='default_song.jpg', upload_to='song_images/'),
        ),
    ]
