# Generated by Django 5.1.2 on 2024-10-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_book_image_movie_image_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default_movie.jpg', upload_to='media/movie_images/'),
        ),
    ]
