# Generated by Django 5.1.2 on 2024-10-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_movie_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
