# Generated by Django 5.1.2 on 2024-10-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readlist',
            old_name='user',
            new_name='readlist_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='mbti_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.mbtitype'),
        ),
    ]
