# Generated by Django 5.1.2 on 2024-11-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_rename_user_readlist_readlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='first_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_books_first', to='website.mbtitype'),
        ),
        migrations.AddField(
            model_name='book',
            name='second_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_books_second', to='website.mbtitype'),
        ),
        migrations.AddField(
            model_name='book',
            name='third_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_books_third', to='website.mbtitype'),
        ),
        migrations.AddField(
            model_name='movie',
            name='first_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_movies_first', to='website.mbtitype'),
        ),
        migrations.AddField(
            model_name='movie',
            name='second_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_movies_second', to='website.mbtitype'),
        ),
        migrations.AddField(
            model_name='movie',
            name='third_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_movies_third', to='website.mbtitype'),
        ),
        migrations.AddField(
            model_name='song',
            name='first_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_songs_first', to='website.mbtitype'),
        ),
        migrations.AddField(
            model_name='song',
            name='second_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_songs_second', to='website.mbtitype'),
        ),
        migrations.AddField(
            model_name='song',
            name='third_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_songs_third', to='website.mbtitype'),
        ),
    ]
